name: null
channels:
  - tmap
  - anaconda
  - defaults
  - conda-forge
  - https://conda.anaconda.org/conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - _py-xgboost-mutex=2.0=cpu_0
  - anyio=4.6.2=py39h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py39h7f8727e_0
  - arrow-cpp=16.1.0=hc1eb8f0_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py39h06a4308_0
  - attrs=24.2.0=py39h06a4308_0
  - aws-c-auth=0.6.19=h5eee18b_0
  - aws-c-cal=0.5.20=hdbd6064_0
  - aws-c-common=0.8.5=h5eee18b_0
  - aws-c-compression=0.2.16=h5eee18b_0
  - aws-c-event-stream=0.2.15=h6a678d5_0
  - aws-c-http=0.6.25=h5eee18b_0
  - aws-c-io=0.13.10=h5eee18b_0
  - aws-c-mqtt=0.7.13=h5eee18b_0
  - aws-c-s3=0.1.51=hdbd6064_0
  - aws-c-sdkutils=0.1.6=h5eee18b_0
  - aws-checksums=0.1.13=h5eee18b_0
  - aws-crt-cpp=0.18.16=h6a678d5_0
  - aws-sdk-cpp=1.10.55=h721c034_0
  - babel=2.11.0=py39h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.3=py39h06a4308_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - bokeh=3.4.3=py39h2f386ee_0
  - boost-cpp=1.82.0=hdb19cb5_2
  - bottleneck=1.4.2=py39ha9d4c09_0
  - brotli=1.0.9=h5eee18b_8
  - brotli-bin=1.0.9=h5eee18b_8
  - brotli-python=1.0.9=py39h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.8.30=hbcca054_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.1=py39h1fdaa30_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.7=py39h06a4308_0
  - cloudpickle=3.0.0=py39h06a4308_0
  - comm=0.2.1=py39h06a4308_0
  - contourpy=1.2.0=py39hdb19cb5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - cytoolz=0.12.2=py39h5eee18b_0
  - dask=2024.5.0=py39h06a4308_0
  - dask-core=2024.5.0=py39h06a4308_0
  - dask-expr=1.1.0=py39h06a4308_0
  - dask-glm=0.3.2=pyhd8ed1ab_0
  - dask-ml=2024.4.4=py39h06a4308_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.6.7=py39h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - distributed=2024.5.0=py39h06a4308_0
  - exceptiongroup=1.2.0=py39h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.3=h6a678d5_0
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.51.0=py39h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - fsspec=2024.6.1=py39h06a4308_0
  - gflags=2.2.2=h6a678d5_1
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - glog=0.5.0=h6a678d5_1
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - h11=0.14.0=py39h06a4308_0
  - h5py=3.12.1=py39hc0802c4_0
  - hdf5=1.12.1=h2b7332f_3
  - heapdict=1.0.1=pyhd3eb1b0_0
  - httpcore=1.0.2=py39h06a4308_0
  - httpx=0.27.0=py39h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py39h06a4308_0
  - importlib-metadata=7.0.1=py39h06a4308_0
  - importlib_metadata=7.0.1=hd3eb1b0_0
  - importlib_resources=6.4.0=py39h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.5=py39h06a4308_0
  - ipython=8.15.0=py39h06a4308_0
  - ipywidgets=8.1.2=py39h06a4308_0
  - jedi=0.19.1=py39h06a4308_0
  - jinja2=3.1.4=py39h06a4308_1
  - joblib=1.4.2=py39h06a4308_0
  - jpeg=9e=h5eee18b_3
  - json5=0.9.25=py39h06a4308_0
  - jsonschema=4.23.0=py39h06a4308_0
  - jsonschema-specifications=2023.7.1=py39h06a4308_0
  - jupyter=1.0.0=py39h06a4308_9
  - jupyter-lsp=2.2.0=py39h06a4308_0
  - jupyter_client=8.6.0=py39h06a4308_0
  - jupyter_console=6.6.3=py39h06a4308_0
  - jupyter_core=5.7.2=py39h06a4308_0
  - jupyter_events=0.10.0=py39h06a4308_0
  - jupyter_server=2.14.1=py39h06a4308_0
  - jupyter_server_terminals=0.4.4=py39h06a4308_1
  - jupyterlab=4.2.5=py39h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.27.3=py39h06a4308_0
  - jupyterlab_widgets=3.0.10=py39h06a4308_0
  - kiwisolver=1.4.4=py39h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=3.0=h295c915_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libclang13=14.0.6=default_he11475f_1
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.9.1=h251f7ec_0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgrpc=1.62.2=h2d74bed_0
  - libiconv=1.16=h5eee18b_3
  - libllvm14=14.0.6=hecde1de_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.0=hdbd6064_0
  - libprotobuf=4.25.3=he621ea3_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libthrift=0.15.0=h1795dd8_2
  - libtiff=4.5.1=h6a678d5_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxgboost=2.1.1=h6a678d5_0
  - libxkbcommon=1.0.1=h097e994_2
  - libxml2=2.13.5=hfdd30dd_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - llvmlite=0.43.0=py39h6a678d5_0
  - locket=1.0.0=py39h06a4308_0
  - lz4=4.3.2=py39h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py39h5eee18b_0
  - matplotlib=3.9.2=py39h06a4308_0
  - matplotlib-base=3.9.2=py39hbfdbfaf_0
  - matplotlib-inline=0.1.6=py39h06a4308_0
  - mistune=2.0.4=py39h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.11=py39h5eee18b_0
  - mkl_random=1.2.8=py39h1128e8f_0
  - msgpack-python=1.0.3=py39hd09550d_0
  - multipledispatch=0.6.0=pyhd8ed1ab_1
  - mysql=8.4.0=h29a9f33_1
  - nbclient=0.8.0=py39h06a4308_0
  - nbconvert=7.16.4=py39h06a4308_0
  - nbformat=5.10.4=py39h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py39h06a4308_0
  - networkx=3.2.1=py39h06a4308_0
  - notebook=7.2.2=py39h06a4308_1
  - notebook-shim=0.2.3=py39h06a4308_0
  - numba=0.60.0=py39h0320e7d_0
  - numexpr=2.10.1=py39h3c60e43_0
  - numpy=1.26.4=py39h5f9d8c6_0
  - numpy-base=1.26.4=py39hb5e798b_0
  - ogdf=1.2.0=h2bc3f7f_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openldap=2.6.4=h42fbc30_0
  - openssl=3.4.0=hb9d3cd8_0
  - orc=2.0.1=h2d29ad5_0
  - overrides=7.4.0=py39h06a4308_0
  - packaging=24.1=py39h06a4308_0
  - pandas=2.2.2=py39h6a678d5_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.4.1=py39h06a4308_0
  - patsy=1.0.1=pyhff2d567_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=11.0.0=py39hfdbf927_0
  - pip=24.2=py39h06a4308_0
  - platformdirs=3.10.0=py39h06a4308_0
  - ply=3.11=py39h06a4308_0
  - prometheus_client=0.21.0=py39h06a4308_0
  - prompt-toolkit=3.0.43=py39h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py39h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-xgboost=2.1.1=py39h06a4308_0
  - pyarrow=16.1.0=py39h1128e8f_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py39h06a4308_1
  - pyparsing=3.2.0=py39h06a4308_0
  - pyqt=5.15.10=py39h6a678d5_0
  - pyqt5-sip=12.13.0=py39h5eee18b_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.20=he870216_1
  - python-dateutil=2.9.0post0=py39h06a4308_2
  - python-fastjsonschema=2.20.0=py39h06a4308_0
  - python-json-logger=2.0.7=py39h06a4308_0
  - python-lmdb=1.4.1=py39h6a678d5_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytz=2024.1=py39h06a4308_0
  - pyyaml=6.0.2=py39h5eee18b_0
  - pyzmq=25.1.2=py39h6a678d5_0
  - qt-main=5.15.2=hb6262e9_11
  - qtconsole=5.6.0=py39h06a4308_0
  - qtpy=2.4.1=py39h06a4308_0
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=py39h06a4308_0
  - requests=2.32.3=py39h06a4308_1
  - rfc3339-validator=0.1.4=py39h06a4308_0
  - rfc3986-validator=0.1.1=py39h06a4308_0
  - rpds-py=0.10.6=py39h4aa5aa6_1
  - s2n=1.3.27=hdbd6064_0
  - scikit-learn=1.5.1=py39h1128e8f_0
  - scipy=1.12.0=py39h5f9d8c6_0
  - seaborn=0.13.2=hd8ed1ab_2
  - seaborn-base=0.13.2=pyhd8ed1ab_2
  - send2trash=1.8.2=py39h06a4308_0
  - setuptools=75.1.0=py39h06a4308_0
  - shap=0.46.0=cpu_py39h9641c6f_1
  - sip=6.7.12=py39h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - slicer=0.0.8=py39h2f386ee_0
  - snappy=1.2.1=h6a678d5_0
  - sniffio=1.3.0=py39h06a4308_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.5=py39h06a4308_0
  - sparse=0.15.4=pyh267e887_1
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.14.4=py39hf3d9206_0
  - tbb=2021.8.0=hdb19cb5_0
  - tblib=1.7.0=pyhd3eb1b0_0
  - terminado=0.17.1=py39h06a4308_0
  - threadpoolctl=3.5.0=py39h2f386ee_0
  - tinycss2=1.2.1=py39h06a4308_0
  - tk=8.6.14=h39e8969_0
  - tmap=1.0.6=py39h2bc3f7f_0
  - tomli=2.0.1=py39h06a4308_0
  - toolz=0.12.0=py39h06a4308_0
  - tornado=6.4.1=py39h5eee18b_0
  - tqdm=4.66.5=py39h2f386ee_0
  - traitlets=5.14.3=py39h06a4308_0
  - typing-extensions=4.11.0=py39h06a4308_0
  - typing_extensions=4.11.0=py39h06a4308_0
  - tzdata=2024b=h04d1e81_0
  - unicodedata2=15.1.0=py39h5eee18b_0
  - urllib3=2.2.3=py39h06a4308_0
  - utf8proc=2.6.1=h5eee18b_1
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py39h06a4308_1
  - websocket-client=1.8.0=py39h06a4308_0
  - wheel=0.44.0=py39h06a4308_0
  - widgetsnbextension=4.0.10=py39h06a4308_0
  - xgboost=2.1.1=py39h06a4308_0
  - xyzservices=2022.9.0=py39h06a4308_1
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zict=3.0.0=py39h06a4308_0
  - zipp=3.20.2=py39h06a4308_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
    - absl-py==2.1.0
    - anndata==0.10.9
    - array-api-compat==1.11.2
    - astunparse==1.6.3
    - dill==0.4.0
    - flatbuffers==24.3.25
    - gast==0.6.0
    - get-annotations==0.1.2
    - google-pasta==0.2.0
    - grpcio==1.68.1
    - keras==3.7.0
    - legacy-api-wrap==1.4.1
    - libclang==18.1.1
    - loompy==3.0.8
    - markdown==3.7
    - markdown-it-py==3.0.0
    - mdurl==0.1.2
    - mhfp==1.9.6
    - ml-dtypes==0.4.1
    - multiprocess==0.70.18
    - namex==0.0.8
    - natsort==8.4.0
    - numpy-groupies==0.11.3
    - opt-einsum==3.4.0
    - optree==0.13.1
    - pathos==0.3.4
    - pox==0.3.6
    - ppft==1.7.7
    - protobuf==5.29.0
    - pynndescent==0.5.13
    - rdkit==2024.3.6
    - rich==13.9.4
    - scanpy==1.10.3
    - session-info==1.0.1
    - stdlib-list==0.11.1
    - tensorboard==2.18.0
    - tensorboard-data-server==0.7.2
    - tensorflow==2.18.0
    - tensorflow-io-gcs-filesystem==0.37.1
    - termcolor==2.5.0
    - umap-learn==0.5.7
    - werkzeug==3.1.3
    - wrapt==1.17.0
prefix: /work/FAC/FBM/DSB/flanglet/tango-bioinf/David/Conda_Env/EDMap_Conda

